name: CursedClasses
version: 0.2.2
main: net.cursedvalley.classes.CursedClasses
api-version: '1.21'
authors: [MRWQLF]
description: Sinif sistemi, sinif silahlari, silah seviyeleri, parti ve para.

commands:
  sinif:
    description: Sinif sec / goster
    usage: /sinif sec <sinif>
  cclass:
    description: Yonetim komutlari
    usage: /cclass ...
    permission: cursedclasses.admin
  parti:
    description: Parti islemleri
    usage: /parti cagir <oyuncu>
  para:
    description: Bakiye islemleri
    usage: /para

permissions:
  cursedclasses.admin:
    default: op
